### ISSUE TITLE
API Documentation Checklist

### ISSUE THREAD

**Issue by twilson63** [hyper63/webcms#9]
- [x] GET /
- [x] POST /api/faqs
- [x] GET /api/faqs
- [x] PUT /api/faqs/{id}
- [x] GET /api/faqs/{id}
- [x] DELETE /api/faqs/{id}
